### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by ckhorne** [magico13/PyEmVue#1]
I've tried to install on two different boxes (raspian and OSX) and both give this eror:

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyemvue
  Downloading https://files.pythonhosted.org/packages/0e/a7/7054fa7d3ec4bc53d8f6f866045e9d1a1d161bda3dc4eb5ed968275ed9d2/pyemvue-0.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-GlBX1M/pyemvue/setup.py", line 3, in <module>
        with open("README.md", "r") as fh:
    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-GlBX1M/pyemvue/
```

Is the package missing README.md?

**Comment by magico13** [comment]
I haven't had issues when I tried installing it with pip on a different computer to test but that obviously doesn't cover all cases. I thought the readme was only needed when building the package not also when installing it. I can try to do some more research in this tonight, I'm obviously very new to making python packages.

**Comment by ckhorne** [comment]
I'm happy to test as needed. This package would be very useful!

**Comment by magico13** [comment]
So I just pushed a new version where the setup.py will ignore the readme file if it can't find it. Go ahead and try that version to see if you get further. I'm intending on setting up a raspberry pi to test as well but haven't quite yet.

**Comment by ckhorne** [comment]
That worked! I was able to install the library on both my raspberry pi and on my OSX box. I haven't had a chance to try out the library yet, but it did confirm that it installed. Thanks!
