### ISSUE TITLE
Installed from HACS, but doesn't list when search. 

### ISSUE THREAD

**Issue by superpanjy** [magico13/PyEmVue#17]
Core: core-2021.5.5
Supervisor: supervisor-2021.04.3
Installed from HACS by following your instruction and restarted. 
But it doesn't list out when search at integration page. 
New folder was added at customer_components after installation.

**Comment by magico13** [comment]
Sorry for the delay, but this repo is for the backing API and not the Home Assistant integration. Make sure you're using the github repo for the Home Assistant integration and not this. If you still have issues, try the things mentioned in the issue linked below and if that doesn't work leave a comment on there. https://github.com/magico13/ha-emporia-vue/issues/19
