### ISSUE TITLE
Usage Channels 1,2,3 individually

### ISSUE THREAD

**Issue by Cuervocartoon** [magico13/PyEmVue#22]
Hi there!

Is there any way to get the usage data individually for channel 1,2,3?

**Comment by magico13** [comment]
Unfortunately there is not direct data for each channel in kw as of right now since each channel isn't broken out in the API. However, if you request amp data it is broken into each separate channel. You could multiply by 120 then to get kw for each leg separately.

**Comment by Cuervocartoon** [comment]
I really appreciate your response and dedication. Best regards
