### ISSUE TITLE
Can this pull from MQTTS?

### ISSUE THREAD

**Issue by crlogic** [magico13/PyEmVue#23]
A few details I found from serial console that smarter people might know what to do with it.  Feel free to delete if not relevant.

Snippets..
```
MQTTComms: MQTT Server Configured: mqtts://a2poo8btpqc3gs-ats.iot.us-east-2.amazonaws.com:8883

MQTTComms: MQTTComms_PublishBinaryReadings Topic: $aws/rules/prodIngestBinaryToSQS/prod/binary/$SERIAL/meter

MQTTComms: TOPIC=prod/minions/emporia/ct/v1/$SERIAL/cmd
MQTTComms: DATA={"cmd":"set","live_meter_updates":60}
MQTTComms: DATA={"cmd":"query_debug"}

MQTTComms: SUBSCRIBE to topic prod/minions/emporia/ct/v1/broadcast/cmd
MQTTComms: SUBSCRIBE to topic prod/minions/emporia/ct/v1/broadcast/fw
MQTTComms: SUBSCRIBE to topic prod/minions/emporia/ct/v1/broadcast/verify

http://fwsrv.emporiaenergy.com:21100
```

plus two plain text certs and one RSA private key pulled from esptool bin backup.

**Comment by magico13** [comment]
Right now there's nothing like this set up for local access. There was some talk on [this forum post](https://www.humblebundle.com/games/humbles-early-access-allstars) but I don't know of any real advancements made on this front. Really hoping for official MQTT access so we can get realtime local data.

**Comment by crkochan** [comment]
What should be a link to forum post is instead a link to a Humble bundle.

**Comment by magico13** [comment]
Hmm, it sure was. Must've had my clipboard out of order, fixed now. Here's the full link

https://community.emporiaenergy.com/topic/api-to-pull-data/#post-7806

**Comment by crlogic** [comment]
Debating a JTAG programmer to pull from the SAMD in hopes of further
probing.

If the ESP32 serial headers are any indication [not being connected], then
the SAMD headers are not connected either and manually probing that IC
would be a pity.

**Comment by magico13** [comment]
Someone mentioned to me, might have been on Reddit, that they've intercepted the serial communication and sent it out via an esp32 to their local network. Let me see if I can find that message.

**Comment by crlogic** [comment]
That would be ideal!

**Comment by magico13** [comment]
Looks like they actually did do a write up of how they connected everything. Might be worth trying to go through their steps and see if it's still writing out that data on the serial line. https://docs.google.com/document/d/1tDGpX2XjyVnq4ThRZn4hKrfLy4UUmnX5uWzNcnqArd4/edit?usp=drivesdk

**Comment by crlogic** [comment]
Is that a Gen1 Vue?

The Gen2 [which I have] does not appear to use the ESP for data
collection.  The SAMD is connected to two multiplexers and the prevailing
theory is that the ESP needs to probe the SAMD for information as I see no
serial input on any pins of the ESP.

I got stuck trying to figure out how that 'probe' operation might work.
Without a datasheet providing hex/bytearray values that the ESP might use
to trigger the SAMD to spit out a measurement, the only thought I have is
pulling a bin from the SAMD.  But that is above my pay grade.

**Comment by magico13** [comment]
I do believe it is a gen 1 which is also what I have. Unfortunately this sort of hardware hacking isn't something I've got any experience with so all I can do is wish you (or anyone else who tries it) luck.

**Comment by crlogic** [comment]
We all have to start somewhere. This is my first time!

The Vue2 appears to be a good lesson for designers. Don't expose the
sensitive IP to an ESP32. The second MCU is a great roadblock for those who
haven't done this before.

**Comment by mitchese** [comment]
Have you determined which lines of the ESP32 are connected to the SAMD? I'm working on reversing this, the project started out as an easy AnalogRead of the expanders from the esp32 ... nope :(  I've pulled a dump of the esp32 firmware (easy), but the samd is possibly above my pay grade as well for reversing.

**Comment by crlogic** [comment]
Someone who I'll call 312 has been poking as well.

I2c between the ESP & SAMD

SAMD Pins to ESP Pins:

Pin 19 to Pin 13 (IO14)
Pin 18 to Pin 11 (IO26)
Pin 16 to Pin 33 (IO21)
Pin 15 to Pin 36 (IO22)

Need to decipher encoding.. type, len, data

"2a 19 100b210080a9c484040041310000e0f3aa4fc5403d9352c043 2a 14
08ab07100b1d10474f422d3564d7403d9829c043"

**Comment by flaviut** [comment]
For the Vue 2, [the pins are also IO21 & IO22](https://flaviutamas.com/2021/reversing-emporia-vue-2#on-board-communications). I go into more detail on everything in that post, and it's likely to be useful in reversing the Vue 1 too.

I also have a [long dump of I2C inputs -> MQTT data outputs here](https://github.com/flaviut/emporia-vue2-reversing/blob/master/example_messages.txt), as well as [a dump of the calibration data from the Vue 2's NVS partition](https://github.com/flaviut/emporia-vue2-reversing/blob/master/nvs.json#L640-L672).

If anyone is interested in reverse engineering this, please have at it!

**Comment by crlogic** [comment]
@flaviut - that is a great blog post. Perhaps this should move to an ESPHome discussion since flashing and I2C is now known. We just need to figure out lambda data parsing..

**Comment by flaviut** [comment]
@crlogic Looks like @Maelstrom96 has figured out the parsing here: https://github.com/flaviut/emporia-vue2-reversing/issues/1#issuecomment-977014050. I don't know if this is the same for the Vue 1, but it's a pretty good place to start.
