### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by Cuervocartoon** [magico13/PyEmVue#26]
Hello

I've worked with the API without trouble but today's msg is:

requests.exceptions.HTTPError: 400 Client Error: Bad Request for URL: https://api.emporiaenergy.com/customers/#####/devices?detailed=true&hierarchy=true

Tha code is:

vue = PyEmVue()
vue.login(username='xxx@xxxcom', password='xxxxx')

dispositivos=vue.get_devices() (Here is the error)
for dispositivo in dispositivos:
    device=vue.populate_device_properties(dispositivo)
    sede=device.device_name
    print(sede)

Any changes in the API maybe?

Than you

**Comment by magico13** [comment]
Update to 0.14.0 and that should go away. Be aware that there are some breaking changes, see the recent releases for more info.

**Comment by Cuervocartoon** [comment]
I'm sorry, I didn't see the update.

Thank you for your reply.
