### ISSUE TITLE
Question: Tempted to buy this device but want opinion please

### ISSUE THREAD

**Issue by scadaguru** [magico13/PyEmVue#28]
I am so much tempted to buy this device to monitor electricity usage along with solar generation. And only reason holding on just because no official data access except their app. If people are happy with this library and not much issues with unofficial API then I want to throw away about $150 to try it out!

I would like to know from you who already using device and using this library to pull/capture data please share experience. I am heavily invested in automation with so many sensors/devices and very much into programming as well so in case needed tweaking I think I can do that as well. 

Appreciate your time and feedback. 
Great work everyone!
Thanks

**Comment by tsuckow** [comment]
I have a script that pulls smart meter data every 5 minutes and puts it in my own database. Their policy is generally that this is all unsupported and could break at any time. They request that you don't make more than 2 requests per minute which is still too often in my opinion. That said, they just sent me an email to inform me that deprecated requests are being made and will stop working soon, so I just swung by to see if there was an update to pyemvue.

**Comment by scadaguru** [comment]
> I have a script that pulls smart meter data every 5 minutes and puts it in my own database. Their policy is generally that this is all unsupported and could break at any time. They request that you don't make more than 2 requests per minute which is still too often in my opinion. That said, they just sent me an email to inform me that deprecated requests are being made and will stop working soon, so I just swung by to see if there was an update to pyemvue.

Appreciate your detailed response.
Seems like I will take little risk and buy 16 sensors device.
Thanks a lot!
