### ISSUE TITLE
Not able to get_devices()

### ISSUE THREAD

**Issue by badreamer** [magico13/PyEmVue#29]
devices = vue.get_devices() now returns the following error for me:

`
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.emporiaenergy.com/customers/XXXXX/devices?detailed=true&hierarchy=true
`

Has the get_devices() API changed?
The login process returns a True, so it does not seem to be login related.

PS: magico13, thanks for PyEmVue, I would not have purchased my device without this.

**Comment by magico13** [comment]
Update to the latest version, there was an API change earlier this week and the latest version fixes it. There were some other breaking changes as well, check the GitHub release notes.

**Comment by badreamer** [comment]
My bad, thought I had the latest version. Old code works. Thanks again for the immediate response!
