### ISSUE TITLE
Link broken to api documentation on pypi.org

### ISSUE THREAD

**Issue by xdaviddx** [magico13/PyEmVue#3]
Your pypi project was linked to on the Emporia website forums.  In the pypi project, there is a link for api documentation that is broken.  

In the mobile version of the pypi page, there is no link to github.  I was able to get the link by changing to desktop mode in my phone's browser.  A link to github in the information you supply on that page might be beneficial for others to find you on github.

Thanks for creating this and documenting their web api.  It would be nice if they would open up the device itself for LAN access.

**Comment by magico13** [comment]
This should be fixed now, though any forks will still point back to the docs here unless they change it in their readme files. Only a very minor "problem".
