### ISSUE TITLE
integration emporia_vue has state class total_increasing, but its state is negative.

### ISSUE THREAD

**Issue by tanbronson** [magico13/PyEmVue#38]
The log in home assistant:

> Logger: homeassistant.components.sensor.recorder
> Source: components/sensor/recorder.py:331
> Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
> First occurred: June 24, 2022 at 7:05:10 PM (2 occurrences)
> Last logged: June 24, 2022 at 7:05:10 PM
> 
> Entity sensor.none_123_1mon from integration emporia_vue has state class total_increasing, but its state is negative. Triggered by state -124.334 with last_updated set to 2022-06-24T22:59:59.999999+00:00. Please report it to the custom component author.
> Entity sensor.none_123_1d from integration emporia_vue has state class total_increasing, but its state is negative. Triggered by state -17.883 with last_updated set to 2022-06-24T22:59:59.999999+00:00. Please report it to the custom component author.

I have solar panels, and it's possible that at 7pm they stop producing much power

**Comment by magico13** [comment]
This is fixed in the release I'm currently testing. That release still has a few bugs I'm trying to sort out but I'll hopefully be able to finish it up soon

**Comment by magico13** [comment]
This was technically under the wrong repo, should have been in https://github.com/magico13/ha-emporia-vue, but it was corrected over there in the last release.
