### ISSUE TITLE
Examples have few typos

### ISSUE THREAD

**Issue by aviadoffer** [magico13/PyEmVue#4]
Awesome project! thank you very much for doing this.

The examples are using _ but should be upper case second word.

The login with tokens example should be 

vue.login(id_token=data['idToken'],
    access_token=data['accessToken'],
    refresh_token=data['refreshToken'],
    token_storage_file='keys.json')

vs id_token , access_token etc.

Thanks much!

**Comment by magico13** [comment]
This should be taken care of now but let me know if you notice any other typos. Thanks!
