### ISSUE TITLE
Outlet API to set Outlets

### ISSUE THREAD

**Issue by Chris-656** [magico13/PyEmVue#56]
I have a question ? Is there a **new** API documentation für emporia ?

I studied the API documentation. Are there any news regarding the outlets ?
I am using node 18.x for creating iobroker.adapter

Is the outlet API working ?
GET /customers/outlets

`
[
    {
        "deviceGid": 1234,
        "outletOn": false,
        "parentDeviceGid": null,
        "parentChannelNum": null
    }
]
`

I get the error code 403. To get the list of outlets I used
`
const url = "https://api.emporiaenergy.com/customers/devices/status";
		const params = {
			headers: {
				authtoken: this._tokens.IdToken
			},
			method: "GET",
		};
`

But is there a way to PUT the data over API in oder to set an outlet On or Off

Used Environment: Javascript, Node in Iobroker, Adapter creation

**Comment by magico13** [comment]
I don't always keep that API docs file up to date. You've found the right GET call but the outlets endpoint should still work for PUT.

Get outlets (and more): 
GET `customers/devices/status`

Update outlet: 
PUT `devices/outlet`
```json
{
    "deviceGid": 12345,
    "outletOn": true
}
```
