### ISSUE TITLE
POWER_WATT was used from emporia_vue, this is a deprecated

### ISSUE THREAD

**Issue by Git-Novice-User** [magico13/PyEmVue#60]
Here is the Error message from HA which has started to show in the logs.
I expect others may start getting this.

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: January 24, 2024 at 11:07:37 PM (2 occurrences)
Last logged: January 24, 2024 at 11:07:37 PM

POWER_WATT was used from emporia_vue, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/magico13/ha-emporia-vue/issues
ENERGY_KILO_WATT_HOUR was used from emporia_vue, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/magico13/ha-emporia-vue/issues

**Comment by magico13** [comment]
This repo is for PyEmVue, not the Home Assistant integration. This warning has already been fixed in the master version of ha-emporia-vue but hasn't been released yet.
