### ISSUE TITLE
Login issues when using google account

### ISSUE THREAD

**Issue by chakachim** [magico13/PyEmVue#78]
When setting up my Emporia I registered using my google account. When trying to connect the API I keep getting the following error:

botocore.errorfactory.UserNotFoundException: An error occurred (UserNotFoundException) when calling the InitiateAuth operation: User does not exist.

**Comment by magico13** [comment]
As of right now federated login isn't supported. I am not sure what it would take to support it, if it's even possible.

The quickest way to get it into Home Assistant is likely to recreate your account. You may be able to create an account with the same email and they might link together automatically.

Let me do a bit more research before you try anything.

**Comment by magico13** [comment]
So I could only test this going the "other" way, but I was able to connect to my existing Emporia account by using Google login, so you might be able to link them the other direction. Try creating an Emporia account with the same email address as your Google account and if it works then you should see your existing devices when you log in. Then you can use your email and password to log into the API.

**Comment by chakachim** [comment]
That worked!  That was an easy enough fix. Thank you
