### ISSUE TITLE
Very interesting

### ISSUE THREAD

**Issue by drinkwater99** [magico13/PyEmVue#9]
I am guessing you have a patched version the Emporia Energy android app which bypasses certificate issues to be able to inspect the traffic done by the app via a proxy ?

**Comment by magico13** [comment]
Pretty much. Specifically I have used HttpCanary on a rooted phone. There was some extra work required to get the details needed for authentication.

**Comment by drinkwater99** [comment]
Thx for the info, I didn't know about HttpCanary, I will give it a try. 
I thought a modified apk would be needed - I did that with the Mysa smart baseboard thermostat android app (which also uses AWS Cognito for auth).
